In [1]:
import numpy as np

ak_list = []

def qr_decomposition(A):
    n = A.shape[0]
    Q = np.eye(n)
    R = A.copy()
    
    for i in range(n - 1):
        x = R[i:, i]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        u = x - e
        v = u / np.linalg.norm(u)
        
        Qi = np.eye(n)
        Qi[i:, i:] -= 2.0 * np.outer(v, v)
        
        R = Qi @ R
        Q = Q @ Qi
    
    return Q, R

def qr_algorithm(A, tol=1e-6):
    n = A.shape[0]
    P = np.eye(n)
    Ak = A.copy()
    
    while np.max(np.abs(np.tril(Ak, -1))) > tol:
        Q, R = qr_decomposition(Ak)
        Ak = R @ Q
        P = P @ Q
        ak_list.append(Ak)
    
    eigenvalues = np.diag(Ak)
    return P, eigenvalues

# Matriz A fornecida
A = np.array([[9, 3, -4, 11],
              [3, 33, -8, -4],
              [-4, -8, 28, 25],
              [11, -4, 25, 73]])

P, eigenvalues = qr_algorithm(A)

# Autovalores
print("Autovalores:", eigenvalues)

# Autovetores
print("Autovetores (colunas de P):")
print(P)

print("\nA cada iteração:")
print(ak_list)


Autovalores: [85.87745758 35.55958866 18.30136537  3.26158838]
Autovetores (colunas de P):
[[ 0.10354247  0.24247012 -0.44317153 -0.8567883 ]
 [-0.12285897  0.89032565  0.43831244  0.01039773]
 [ 0.39964851 -0.30905528  0.74992329 -0.42706083]
 [ 0.90247753  0.2302462  -0.22157675  0.28883341]]

A cada iteração:
[array([[ 46.68530371,  -9.58537194,  26.71811262,  -8.36692254],
       [ -9.58537194,  43.32263722, -19.63432198,   3.24128691],
       [ 26.71811262, -19.63432198,  48.05308863,  -5.08080238],
       [ -8.36692254,   3.24128691,  -5.08080238,   4.93897044]]), array([[ 7.69157592e+01, -1.65987828e+01,  1.15077516e+01,
         5.03725399e-01],
       [-1.65987828e+01,  4.22110362e+01, -4.21818002e+00,
         5.08839470e-02],
       [ 1.15077516e+01, -4.21818002e+00,  2.05982895e+01,
        -3.04300244e-01],
       [ 5.03725399e-01,  5.08839470e-02, -3.04300244e-01,
         3.27491508e+00]]), array([[ 8.44048582e+01, -8.16515518e+00,  2.68919194e+00,
        -2.06668056e-0